### ISSUE TITLE
Discover New Devices

### ISSUE THREAD

**Issue by ryaeng** [trir262/PowerShell-SL1#5]
Tom,

I'm interested in discovering new devices in Science Logic and I'd like to use your code as a base. That being said, your code is more complex than other PowerShell code that I've seen. Any recommendations on how I should start? I'd like to follow your layout so the code may remain consistent.

Thank you

**Comment by trir262** [comment]
Hello Ryan,
Thank you for your interest! I hope we can really build something cool here! 
I am very active on the ScienceLogic Slack User Group: https://bit.ly/2wlQAUz so if you'd like help, please join there and we'll discuss it.

Again thank you for your contribution already!

**Comment by trir262** [comment]
#21 needs to be implemented before this can be developed.

**Comment by trir262** [comment]
#21 is implemented. development can start for this one.

**Comment by trir262** [comment]
Minimum JSON required to create a proper discovery session looks like this:
```json
{
    "organization":  "/api/organization/1",
    "aligned_collector":  "/api/appliance/1",
    "name":  "somename",
    "credentials":  [
                        "/api/credential/snmp/1"
                    ],
    "ip_lists":  [
                     {
                         "start_ip":  "1.2.3.4",
                         "end_ip":  "1.2.3.4"
                     }
                 ]
}
```

**Comment by ryaeng** [comment]
@trir262 I'm still interested in working on this one. My thoughts are that I would begin by by submitting the discovery with one device up front and then iterate from there. Thoughts?

**Comment by trir262** [comment]
Archived repo
