### ISSUE TITLE
Add function Get-SL1Credential to get different types of credentials from ScienceLogic

### ISSUE THREAD

**Issue by trir262** [trir262/PowerShell-SL1#7]
ScienceLogic API allows retrieving stored credentials via /api/credential. The function Get-SL1Credential should be able to retrieve any kind of credential (ssh, snippet, database, soap, ...) and output the interesting fields, depending on the credential type.

The function should have the following parameter sets:
* (default): Get-SL1Credential -Type <string> -Filter <string>
* Get-SL1Credential -Type <string> -Id <int>

**Comment by ryaeng** [comment]
@trir262 This is what I've gotten so far. I was having troubles with the function last night after calling Import-Module. Please advise.

https://github.com/ryaeng/PowerShell-SL1/tree/get_credential
